name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        go-version: [1.16.x]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          go build -o file-lookup
          mv file-lookup ${{ github.workspace }}/file-lookup
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file-lookup-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/file-lookup
